// The wire between a graphene agent and the graphene server.
//
// The agent dials OUT to the server and keeps one bidirectional stream
// open: it authenticates with its scoped token (gRPC metadata
// "authorization: Bearer <token>"), introduces itself with Hello, then
// sends heartbeats and container reports; the server sends container
// commands. The agent listens on no ports and never speaks Temporal —
// the user code inside the containers it hosts does.
//
// The contract lives in the agent repository; the server imports the
// generated package and implements the service.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/agent/v1/agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentAPI_Session_FullMethodName = "/agent.v1.AgentAPI/Session"
)

// AgentAPIClient is the client API for AgentAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentAPI is served by the graphene server; agents are the clients.
type AgentAPIClient interface {
	// Session is the single long-lived bidirectional stream of one agent.
	// First agent message MUST be Hello; first server message is HelloAck.
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SessionRequest, SessionResponse], error)
}

type agentAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentAPIClient(cc grpc.ClientConnInterface) AgentAPIClient {
	return &agentAPIClient{cc}
}

func (c *agentAPIClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SessionRequest, SessionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentAPI_ServiceDesc.Streams[0], AgentAPI_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SessionRequest, SessionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentAPI_SessionClient = grpc.BidiStreamingClient[SessionRequest, SessionResponse]

// AgentAPIServer is the server API for AgentAPI service.
// All implementations must embed UnimplementedAgentAPIServer
// for forward compatibility.
//
// AgentAPI is served by the graphene server; agents are the clients.
type AgentAPIServer interface {
	// Session is the single long-lived bidirectional stream of one agent.
	// First agent message MUST be Hello; first server message is HelloAck.
	Session(grpc.BidiStreamingServer[SessionRequest, SessionResponse]) error
	mustEmbedUnimplementedAgentAPIServer()
}

// UnimplementedAgentAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentAPIServer struct{}

func (UnimplementedAgentAPIServer) Session(grpc.BidiStreamingServer[SessionRequest, SessionResponse]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedAgentAPIServer) mustEmbedUnimplementedAgentAPIServer() {}
func (UnimplementedAgentAPIServer) testEmbeddedByValue()                  {}

// UnsafeAgentAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentAPIServer will
// result in compilation errors.
type UnsafeAgentAPIServer interface {
	mustEmbedUnimplementedAgentAPIServer()
}

func RegisterAgentAPIServer(s grpc.ServiceRegistrar, srv AgentAPIServer) {
	// If the following call panics, it indicates UnimplementedAgentAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentAPI_ServiceDesc, srv)
}

func _AgentAPI_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentAPIServer).Session(&grpc.GenericServerStream[SessionRequest, SessionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentAPI_SessionServer = grpc.BidiStreamingServer[SessionRequest, SessionResponse]

// AgentAPI_ServiceDesc is the grpc.ServiceDesc for AgentAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.AgentAPI",
	HandlerType: (*AgentAPIServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _AgentAPI_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agent/v1/agent.proto",
}
