// The wire between a graphene agent and the graphene server.
//
// The agent dials OUT to the server and keeps one bidirectional stream
// open: it authenticates with its scoped token (gRPC metadata
// "authorization: Bearer <token>"), introduces itself with Hello, then
// sends heartbeats and container reports; the server sends container
// commands. The agent listens on no ports and never speaks Temporal —
// the user code inside the containers it hosts does.
//
// The contract lives in the agent repository; the server imports the
// generated package and implements the service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: api/agent/v1/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContainerState is the lifecycle of a hosted container.
type ContainerState int32

const (
	ContainerState_CONTAINER_STATE_UNSPECIFIED ContainerState = 0
	ContainerState_CONTAINER_STATE_PULLING     ContainerState = 1
	ContainerState_CONTAINER_STATE_RUNNING     ContainerState = 2
	ContainerState_CONTAINER_STATE_STOPPED     ContainerState = 3
	ContainerState_CONTAINER_STATE_FAILED      ContainerState = 4
)

// Enum value maps for ContainerState.
var (
	ContainerState_name = map[int32]string{
		0: "CONTAINER_STATE_UNSPECIFIED",
		1: "CONTAINER_STATE_PULLING",
		2: "CONTAINER_STATE_RUNNING",
		3: "CONTAINER_STATE_STOPPED",
		4: "CONTAINER_STATE_FAILED",
	}
	ContainerState_value = map[string]int32{
		"CONTAINER_STATE_UNSPECIFIED": 0,
		"CONTAINER_STATE_PULLING":     1,
		"CONTAINER_STATE_RUNNING":     2,
		"CONTAINER_STATE_STOPPED":     3,
		"CONTAINER_STATE_FAILED":      4,
	}
)

func (x ContainerState) Enum() *ContainerState {
	p := new(ContainerState)
	*p = x
	return p
}

func (x ContainerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (ContainerState) Type() protoreflect.EnumType {
	return &file_api_agent_v1_agent_proto_enumTypes[0]
}

func (x ContainerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerState.Descriptor instead.
func (ContainerState) EnumDescriptor() ([]byte, []int) {
	return file_api_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

// SessionRequest is everything an agent sends.
type SessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*SessionRequest_Hello
	//	*SessionRequest_Heartbeat
	//	*SessionRequest_ContainerReport
	//	*SessionRequest_CommandResult
	Body          isSessionRequest_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_api_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *SessionRequest) GetBody() isSessionRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SessionRequest) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*SessionRequest_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *SessionRequest) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*SessionRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *SessionRequest) GetContainerReport() *ContainerReport {
	if x != nil {
		if x, ok := x.Body.(*SessionRequest_ContainerReport); ok {
			return x.ContainerReport
		}
	}
	return nil
}

func (x *SessionRequest) GetCommandResult() *CommandResult {
	if x != nil {
		if x, ok := x.Body.(*SessionRequest_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

type isSessionRequest_Body interface {
	isSessionRequest_Body()
}

type SessionRequest_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type SessionRequest_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type SessionRequest_ContainerReport struct {
	ContainerReport *ContainerReport `protobuf:"bytes,3,opt,name=container_report,json=containerReport,proto3,oneof"`
}

type SessionRequest_CommandResult struct {
	CommandResult *CommandResult `protobuf:"bytes,4,opt,name=command_result,json=commandResult,proto3,oneof"`
}

func (*SessionRequest_Hello) isSessionRequest_Body() {}

func (*SessionRequest_Heartbeat) isSessionRequest_Body() {}

func (*SessionRequest_ContainerReport) isSessionRequest_Body() {}

func (*SessionRequest_CommandResult) isSessionRequest_Body() {}

// SessionResponse is everything the server sends.
type SessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*SessionResponse_HelloAck
	//	*SessionResponse_EnsureContainer
	//	*SessionResponse_StopContainer
	Body          isSessionResponse_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_api_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *SessionResponse) GetBody() isSessionResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SessionResponse) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Body.(*SessionResponse_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *SessionResponse) GetEnsureContainer() *EnsureContainer {
	if x != nil {
		if x, ok := x.Body.(*SessionResponse_EnsureContainer); ok {
			return x.EnsureContainer
		}
	}
	return nil
}

func (x *SessionResponse) GetStopContainer() *StopContainer {
	if x != nil {
		if x, ok := x.Body.(*SessionResponse_StopContainer); ok {
			return x.StopContainer
		}
	}
	return nil
}

type isSessionResponse_Body interface {
	isSessionResponse_Body()
}

type SessionResponse_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type SessionResponse_EnsureContainer struct {
	EnsureContainer *EnsureContainer `protobuf:"bytes,2,opt,name=ensure_container,json=ensureContainer,proto3,oneof"`
}

type SessionResponse_StopContainer struct {
	StopContainer *StopContainer `protobuf:"bytes,3,opt,name=stop_container,json=stopContainer,proto3,oneof"`
}

func (*SessionResponse_HelloAck) isSessionResponse_Body() {}

func (*SessionResponse_EnsureContainer) isSessionResponse_Body() {}

func (*SessionResponse_StopContainer) isSessionResponse_Body() {}

// Hello introduces the agent: which agent record it embodies and what
// the machine looks like.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Facts         *Facts                 `protobuf:"bytes,3,opt,name=facts,proto3" json:"facts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_api_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetFacts() *Facts {
	if x != nil {
		return x.Facts
	}
	return nil
}

// Facts is the bounded machine inventory reported at Hello and refreshed
// on reconnect. The server stores the facts blob outside the machine
// record and keeps only its digest there.
type Facts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Cpus          uint32                 `protobuf:"varint,4,opt,name=cpus,proto3" json:"cpus,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Addresses     []string               `protobuf:"bytes,6,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Facts) Reset() {
	*x = Facts{}
	mi := &file_api_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facts) ProtoMessage() {}

func (x *Facts) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Facts.ProtoReflect.Descriptor instead.
func (*Facts) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Facts) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Facts) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Facts) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Facts) GetCpus() uint32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *Facts) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *Facts) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

// Heartbeat proves liveness and carries the current container set, so a
// reconnecting server learns the machine's state without asking.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerReport     `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_api_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetContainers() []*ContainerReport {
	if x != nil {
		return x.Containers
	}
	return nil
}

// HelloAck accepts the agent and tunes its cadence.
type HelloAck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatSeconds uint32                 `protobuf:"varint,1,opt,name=heartbeat_seconds,json=heartbeatSeconds,proto3" json:"heartbeat_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_api_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *HelloAck) GetHeartbeatSeconds() uint32 {
	if x != nil {
		return x.HeartbeatSeconds
	}
	return 0
}

// ContainerSpec describes one hosted container: the user worker of one
// run on this machine. Env carries wiring only (server address, role,
// ids, run-scoped token) — secret VALUES never appear here.
type ContainerSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerSpec) Reset() {
	*x = ContainerSpec{}
	mi := &file_api_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerSpec) ProtoMessage() {}

func (x *ContainerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerSpec.ProtoReflect.Descriptor instead.
func (*ContainerSpec) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerSpec) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ContainerSpec) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ContainerSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// ContainerReport tells the server where one container is in its life.
type ContainerReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	State         ContainerState         `protobuf:"varint,3,opt,name=state,proto3,enum=agent.v1.ContainerState" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerReport) Reset() {
	*x = ContainerReport{}
	mi := &file_api_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerReport) ProtoMessage() {}

func (x *ContainerReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerReport.ProtoReflect.Descriptor instead.
func (*ContainerReport) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ContainerReport) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ContainerReport) GetState() ContainerState {
	if x != nil {
		return x.State
	}
	return ContainerState_CONTAINER_STATE_UNSPECIFIED
}

func (x *ContainerReport) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// EnsureContainer asks the agent to bring the container up (pull if
// missing, start if stopped); ensuring a running container is a no-op.
type EnsureContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Spec          *ContainerSpec         `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureContainer) Reset() {
	*x = EnsureContainer{}
	mi := &file_api_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureContainer) ProtoMessage() {}

func (x *EnsureContainer) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureContainer.ProtoReflect.Descriptor instead.
func (*EnsureContainer) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *EnsureContainer) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *EnsureContainer) GetSpec() *ContainerSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// StopContainer asks the agent to terminate and remove the container of
// (machine × run); stopping an absent container is a no-op.
type StopContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopContainer) Reset() {
	*x = StopContainer{}
	mi := &file_api_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContainer) ProtoMessage() {}

func (x *StopContainer) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContainer.ProtoReflect.Descriptor instead.
func (*StopContainer) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *StopContainer) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *StopContainer) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StopContainer) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

// CommandResult reports completion of one command; empty error means
// success. State changes travel separately as ContainerReport.
type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_api_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_agent_v1_agent_proto protoreflect.FileDescriptor

const file_api_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x18api/agent/v1/agent.proto\x12\bagent.v1\"\x80\x02\n" +
	"\x0eSessionRequest\x12'\n" +
	"\x05hello\x18\x01 \x01(\v2\x0f.agent.v1.HelloH\x00R\x05hello\x123\n" +
	"\theartbeat\x18\x02 \x01(\v2\x13.agent.v1.HeartbeatH\x00R\theartbeat\x12F\n" +
	"\x10container_report\x18\x03 \x01(\v2\x19.agent.v1.ContainerReportH\x00R\x0fcontainerReport\x12@\n" +
	"\x0ecommand_result\x18\x04 \x01(\v2\x17.agent.v1.CommandResultH\x00R\rcommandResultB\x06\n" +
	"\x04body\"\xd6\x01\n" +
	"\x0fSessionResponse\x121\n" +
	"\thello_ack\x18\x01 \x01(\v2\x12.agent.v1.HelloAckH\x00R\bhelloAck\x12F\n" +
	"\x10ensure_container\x18\x02 \x01(\v2\x19.agent.v1.EnsureContainerH\x00R\x0fensureContainer\x12@\n" +
	"\x0estop_container\x18\x03 \x01(\v2\x17.agent.v1.StopContainerH\x00R\rstopContainerB\x06\n" +
	"\x04body\"n\n" +
	"\x05Hello\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12%\n" +
	"\x05facts\x18\x03 \x01(\v2\x0f.agent.v1.FactsR\x05facts\"\x9c\x01\n" +
	"\x05Facts\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x12\n" +
	"\x04cpus\x18\x04 \x01(\rR\x04cpus\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x04R\vmemoryBytes\x12\x1c\n" +
	"\taddresses\x18\x06 \x03(\tR\taddresses\"F\n" +
	"\tHeartbeat\x129\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x19.agent.v1.ContainerReportR\n" +
	"containers\"7\n" +
	"\bHelloAck\x12+\n" +
	"\x11heartbeat_seconds\x18\x01 \x01(\rR\x10heartbeatSeconds\"\xc3\x01\n" +
	"\rContainerSpec\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x122\n" +
	"\x03env\x18\x04 \x03(\v2 .agent.v1.ContainerSpec.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x01\n" +
	"\x0fContainerReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12.\n" +
	"\x05state\x18\x03 \x01(\x0e2\x18.agent.v1.ContainerStateR\x05state\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"]\n" +
	"\x0fEnsureContainer\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12+\n" +
	"\x04spec\x18\x02 \x01(\v2\x17.agent.v1.ContainerSpecR\x04spec\"`\n" +
	"\rStopContainer\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\"D\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*\xa4\x01\n" +
	"\x0eContainerState\x12\x1f\n" +
	"\x1bCONTAINER_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CONTAINER_STATE_PULLING\x10\x01\x12\x1b\n" +
	"\x17CONTAINER_STATE_RUNNING\x10\x02\x12\x1b\n" +
	"\x17CONTAINER_STATE_STOPPED\x10\x03\x12\x1a\n" +
	"\x16CONTAINER_STATE_FAILED\x10\x042N\n" +
	"\bAgentAPI\x12B\n" +
	"\aSession\x12\x18.agent.v1.SessionRequest\x1a\x19.agent.v1.SessionResponse(\x010\x01B2Z0github.com/graphene-ci/agent/pkg/agentpb;agentpbb\x06proto3"

var (
	file_api_agent_v1_agent_proto_rawDescOnce sync.Once
	file_api_agent_v1_agent_proto_rawDescData []byte
)

func file_api_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_api_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_api_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agent_v1_agent_proto_rawDesc), len(file_api_agent_v1_agent_proto_rawDesc)))
	})
	return file_api_agent_v1_agent_proto_rawDescData
}

var file_api_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_agent_v1_agent_proto_goTypes = []any{
	(ContainerState)(0),     // 0: agent.v1.ContainerState
	(*SessionRequest)(nil),  // 1: agent.v1.SessionRequest
	(*SessionResponse)(nil), // 2: agent.v1.SessionResponse
	(*Hello)(nil),           // 3: agent.v1.Hello
	(*Facts)(nil),           // 4: agent.v1.Facts
	(*Heartbeat)(nil),       // 5: agent.v1.Heartbeat
	(*HelloAck)(nil),        // 6: agent.v1.HelloAck
	(*ContainerSpec)(nil),   // 7: agent.v1.ContainerSpec
	(*ContainerReport)(nil), // 8: agent.v1.ContainerReport
	(*EnsureContainer)(nil), // 9: agent.v1.EnsureContainer
	(*StopContainer)(nil),   // 10: agent.v1.StopContainer
	(*CommandResult)(nil),   // 11: agent.v1.CommandResult
	nil,                     // 12: agent.v1.ContainerSpec.EnvEntry
}
var file_api_agent_v1_agent_proto_depIdxs = []int32{
	3,  // 0: agent.v1.SessionRequest.hello:type_name -> agent.v1.Hello
	5,  // 1: agent.v1.SessionRequest.heartbeat:type_name -> agent.v1.Heartbeat
	8,  // 2: agent.v1.SessionRequest.container_report:type_name -> agent.v1.ContainerReport
	11, // 3: agent.v1.SessionRequest.command_result:type_name -> agent.v1.CommandResult
	6,  // 4: agent.v1.SessionResponse.hello_ack:type_name -> agent.v1.HelloAck
	9,  // 5: agent.v1.SessionResponse.ensure_container:type_name -> agent.v1.EnsureContainer
	10, // 6: agent.v1.SessionResponse.stop_container:type_name -> agent.v1.StopContainer
	4,  // 7: agent.v1.Hello.facts:type_name -> agent.v1.Facts
	8,  // 8: agent.v1.Heartbeat.containers:type_name -> agent.v1.ContainerReport
	12, // 9: agent.v1.ContainerSpec.env:type_name -> agent.v1.ContainerSpec.EnvEntry
	0,  // 10: agent.v1.ContainerReport.state:type_name -> agent.v1.ContainerState
	7,  // 11: agent.v1.EnsureContainer.spec:type_name -> agent.v1.ContainerSpec
	1,  // 12: agent.v1.AgentAPI.Session:input_type -> agent.v1.SessionRequest
	2,  // 13: agent.v1.AgentAPI.Session:output_type -> agent.v1.SessionResponse
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_agent_v1_agent_proto_init() }
func file_api_agent_v1_agent_proto_init() {
	if File_api_agent_v1_agent_proto != nil {
		return
	}
	file_api_agent_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*SessionRequest_Hello)(nil),
		(*SessionRequest_Heartbeat)(nil),
		(*SessionRequest_ContainerReport)(nil),
		(*SessionRequest_CommandResult)(nil),
	}
	file_api_agent_v1_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*SessionResponse_HelloAck)(nil),
		(*SessionResponse_EnsureContainer)(nil),
		(*SessionResponse_StopContainer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agent_v1_agent_proto_rawDesc), len(file_api_agent_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_api_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_api_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_api_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_api_agent_v1_agent_proto = out.File
	file_api_agent_v1_agent_proto_goTypes = nil
	file_api_agent_v1_agent_proto_depIdxs = nil
}
